name: pull_request_check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    if: github.repository == 'Adpro-Team/GKD_THS_List'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1

      - uses: pnpm/action-setup@v3

      - name: Ensure Files Changed
        uses: danieljimeneznz/ensure-files-changed@v4.1.1
        with:
          require-changes-to: |
            list.ts
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: pnpm check
